# An environment to develop, build, test, and document bmi-geotiff.
name: geotiff
channels:
  - conda-forge
dependencies:
  - python >=3.9
  - pip
  - pyyaml
  - rioxarray
  - rasterio >=1.0
  - bmipy
  - nox
  - pytest
  - pytest-cov
  - pytest-datadir
  - coveralls
  - bmi-tester
  - sphinx
  - recommonmark
  - pandoc
  - notebook
  - matplotlib
  - cartopy
  - build
  - twine
  - zest.releaser
